# WorkflowNo_1057
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1057
doc: A workflow including the tool(s) MeroX, CrosstalkDB, MSiReader, PEAKS DB, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
steps:
  MeroX_01:
    run: add-path-to-the-implementation/MeroX.cwl 
    in:
      MeroX_in_1: input_3
      MeroX_in_2: input_2
    out: [MeroX_out_1]
  CrosstalkDB_02:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: MeroX_01/MeroX_out_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  MSiReader_03:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: CrosstalkDB_02/CrosstalkDB_out_2
    out: [MSiReader_out_1, MSiReader_out_2]
  PEAKS DB_04:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_3
      PEAKS DB_in_2: input_2
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: MSiReader_03/MSiReader_out_2
      OpenMS_in_2: input_2
      OpenMS_in_3: PEAKS DB_04/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3652" # dta
    outputSource: OpenMS_05/OpenMS_out_1
