# WorkflowNo_115
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_115
doc: A workflow including the tool(s) PECA, GenePattern, msgfdb2pepxml, XTandemPipeline, Multi-Q.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1638" # cel
  input_2:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  PECA_01:
    run: add-path-to-the-implementation/PECA.cwl 
    in:
      PECA_in_1: input_1
    out: [PECA_out_1, PECA_out_2]
  GenePattern_02:
    run: add-path-to-the-implementation/GenePattern.cwl 
    in:
      GenePattern_in_1: PECA_01/PECA_out_1
    out: [GenePattern_out_1]
  msgfdb2pepxml_03:
    run: add-path-to-the-implementation/msgfdb2pepxml.cwl 
    in:
      msgfdb2pepxml_in_1: input_2
      msgfdb2pepxml_in_2: GenePattern_02/GenePattern_out_1
      msgfdb2pepxml_in_3: input_3
    out: [msgfdb2pepxml_out_1]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: msgfdb2pepxml_03/msgfdb2pepxml_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Multi-Q_05:
    run: add-path-to-the-implementation/Multi-Q.cwl 
    in:
      Multi-Q_in_1: input_2
      Multi-Q_in_2: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Multi-Q_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3311" # RNAML
    outputSource: Multi-Q_05/Multi-Q_out_1
