# WorkflowNo_1704
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1704
doc: A workflow including the tool(s) HX-Express, Graph Extract, MS-Fit, OpenMS, DIA-Umpire.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_2:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  HX-Express_01:
    run: add-path-to-the-implementation/HX-Express.cwl 
    in:
      HX-Express_in_1: input_1
    out: [HX-Express_out_1, HX-Express_out_2]
  Graph Extract_02:
    run: add-path-to-the-implementation/Graph Extract.cwl 
    in:
      Graph Extract_in_1: HX-Express_01/HX-Express_out_1
    out: [Graph Extract_out_1]
  MS-Fit_03:
    run: add-path-to-the-implementation/MS-Fit.cwl 
    in:
      MS-Fit_in_1: Graph Extract_02/Graph Extract_out_1
    out: [MS-Fit_out_1]
  OpenMS_04:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_2
      OpenMS_in_3: MS-Fit_03/MS-Fit_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  DIA-Umpire_05:
    run: add-path-to-the-implementation/DIA-Umpire.cwl 
    in:
      DIA-Umpire_in_1: input_1
      DIA-Umpire_in_2: OpenMS_04/OpenMS_out_2
      DIA-Umpire_in_3: input_3
    out: [DIA-Umpire_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3162" # MAGE-TAB
    outputSource: DIA-Umpire_05/DIA-Umpire_out_1
