# WorkflowNo_1242
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1242
doc: A workflow including the tool(s) XTandemPipeline, DeconMSn, protk, XTandemPipeline, Quant.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3711" # X!Tandem XML
  input_2:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  XTandemPipeline_01:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: input_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  DeconMSn_02:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_2
      DeconMSn_in_2: input_2
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  protk_03:
    run: add-path-to-the-implementation/protk.cwl 
    in:
      protk_in_1: input_3
      protk_in_2: XTandemPipeline_01/XTandemPipeline_out_1
    out: [protk_out_1, protk_out_2]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: protk_03/protk_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Quant_05:
    run: add-path-to-the-implementation/Quant.cwl 
    in:
      Quant_in_1: DeconMSn_02/DeconMSn_out_3
      Quant_in_2: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Quant_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3468" # xls
    outputSource: Quant_05/Quant_out_1
