# WorkflowNo_247
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_247
doc: A workflow including the tool(s) MaxQuant, MSiReader, ICPLQuant, IsobariQ, LimmaRP.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3682" # imzML metadata file
  input_2:
    type: File
    format: "http://edamontology.org/format_3620" # xlsx
  input_3:
    type: File
    format: "http://edamontology.org/format_3713" # Mascot .dat file
steps:
  MaxQuant_01:
    run: add-path-to-the-implementation/MaxQuant.cwl 
    in:
      MaxQuant_in_1: input_2
    out: [MaxQuant_out_1, MaxQuant_out_2]
  MSiReader_02:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: MaxQuant_01/MaxQuant_out_1
    out: [MSiReader_out_1, MSiReader_out_2]
  ICPLQuant_03:
    run: add-path-to-the-implementation/ICPLQuant.cwl 
    in:
      ICPLQuant_in_1: input_1
      ICPLQuant_in_2: MSiReader_02/MSiReader_out_2
      ICPLQuant_in_3: input_3
    out: [ICPLQuant_out_1]
  IsobariQ_04:
    run: add-path-to-the-implementation/IsobariQ.cwl 
    in:
      IsobariQ_in_1: input_3
    out: [IsobariQ_out_1]
  LimmaRP_05:
    run: add-path-to-the-implementation/LimmaRP.cwl 
    in:
      LimmaRP_in_1: ICPLQuant_03/ICPLQuant_out_1
      LimmaRP_in_2: IsobariQ_04/IsobariQ_out_1
    out: [LimmaRP_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3508" # PDF
    outputSource: LimmaRP_05/LimmaRP_out_1
