# WorkflowNo_56
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_56
doc: A workflow including the tool(s) PChopper, esimsa2D, esimsa, PeptideProphet, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_3652" # dta
  input_3:
    type: File
    format: "http://edamontology.org/format_2532" # GenBank-HTML
steps:
  PChopper_01:
    run: add-path-to-the-implementation/PChopper.cwl 
    in:
      PChopper_in_1: input_1
    out: [PChopper_out_1]
  esimsa2D_02:
    run: add-path-to-the-implementation/esimsa2D.cwl 
    in:
      esimsa2D_in_1: input_1
      esimsa2D_in_2: PChopper_01/PChopper_out_1
      esimsa2D_in_3: PChopper_01/PChopper_out_1
    out: [esimsa2D_out_1, esimsa2D_out_2, esimsa2D_out_3]
  esimsa_03:
    run: add-path-to-the-implementation/esimsa.cwl 
    in:
      esimsa_in_1: input_1
      esimsa_in_2: esimsa2D_02/esimsa2D_out_2
      esimsa_in_3: esimsa2D_02/esimsa2D_out_2
    out: [esimsa_out_1, esimsa_out_2, esimsa_out_3]
  PeptideProphet_04:
    run: add-path-to-the-implementation/PeptideProphet.cwl 
    in:
      PeptideProphet_in_1: input_3
    out: [PeptideProphet_out_1]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: esimsa_03/esimsa_out_2
      OpenMS_in_2: input_2
      OpenMS_in_3: PeptideProphet_04/PeptideProphet_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
    outputSource: OpenMS_05/OpenMS_out_1
