# WorkflowNo_736
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_736
doc: A workflow including the tool(s) decoy.pl, PEAKS DB, Mayu, XTandemPipeline, Libra.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_3652" # dta
  input_3:
    type: File
    format: "http://edamontology.org/format_2310" # FASTA-HTML
steps:
  decoy.pl_01:
    run: add-path-to-the-implementation/decoy.pl.cwl 
    in:
      decoy.pl_in_1: input_3
    out: [decoy.pl_out_1]
  PEAKS DB_02:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_2
      PEAKS DB_in_2: decoy.pl_01/decoy.pl_out_1
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  Mayu_03:
    run: add-path-to-the-implementation/Mayu.cwl 
    in:
      Mayu_in_1: input_1
      Mayu_in_2: PEAKS DB_02/PEAKS DB_out_1
    out: [Mayu_out_1]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: Mayu_03/Mayu_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Libra_05:
    run: add-path-to-the-implementation/Libra.cwl 
    in:
      Libra_in_1: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Libra_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: Libra_05/Libra_out_1
