# WorkflowNo_55
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_55
doc: A workflow including the tool(s) MSD File Reader, Xtractor, Sirius, PECAN (PEptide-Centric Analysis), Mascot Server.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_2:
    type: File
    format: "http://edamontology.org/format_3162" # MAGE-TAB
  input_3:
    type: File
    format: "http://edamontology.org/format_1336" # dhf
steps:
  MSD File Reader_01:
    run: add-path-to-the-implementation/MSD File Reader.cwl 
    in: []
    out: [MSD File Reader_out_1]
  Xtractor_02:
    run: add-path-to-the-implementation/Xtractor.cwl 
    in:
      Xtractor_in_1: input_3
      Xtractor_in_2: MSD File Reader_01/MSD File Reader_out_1
      Xtractor_in_3: input_3
    out: [Xtractor_out_1, Xtractor_out_2, Xtractor_out_3]
  Sirius_03:
    run: add-path-to-the-implementation/Sirius.cwl 
    in:
      Sirius_in_1: Xtractor_02/Xtractor_out_1
    out: [Sirius_out_1, Sirius_out_2]
  PECAN (PEptide-Centric Analysis)_04:
    run: add-path-to-the-implementation/PECAN (PEptide-Centric Analysis).cwl 
    in:
      PECAN (PEptide-Centric Analysis)_in_1: input_1
      PECAN (PEptide-Centric Analysis)_in_2: input_2
    out: [PECAN (PEptide-Centric Analysis)_out_1, PECAN (PEptide-Centric Analysis)_out_2]
  Mascot Server_05:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: Sirius_03/Sirius_out_2
      Mascot Server_in_2: PECAN (PEptide-Centric Analysis)_04/PECAN (PEptide-Centric Analysis)_out_2
    out: [Mascot Server_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: Mascot Server_05/Mascot Server_out_1
