# WorkflowNo_413
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_413
doc: A workflow including the tool(s) InDigestion, DeconMSn, PECAN (PEptide-Centric Analysis), Mascot Server, msaccess.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_2:
    type: File
    format: "http://edamontology.org/format_1972" # NCBI format
  input_3:
    type: File
    format: "http://edamontology.org/format_3712" # Thermo RAW
steps:
  InDigestion_01:
    run: add-path-to-the-implementation/InDigestion.cwl 
    in:
      InDigestion_in_1: input_2
    out: [InDigestion_out_1, InDigestion_out_2, InDigestion_out_3]
  DeconMSn_02:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_3
      DeconMSn_in_2: input_3
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  PECAN (PEptide-Centric Analysis)_03:
    run: add-path-to-the-implementation/PECAN (PEptide-Centric Analysis).cwl 
    in:
      PECAN (PEptide-Centric Analysis)_in_1: input_1
      PECAN (PEptide-Centric Analysis)_in_2: InDigestion_01/InDigestion_out_3
    out: [PECAN (PEptide-Centric Analysis)_out_1, PECAN (PEptide-Centric Analysis)_out_2]
  Mascot Server_04:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: DeconMSn_02/DeconMSn_out_1
      Mascot Server_in_2: PECAN (PEptide-Centric Analysis)_03/PECAN (PEptide-Centric Analysis)_out_2
    out: [Mascot Server_out_1]
  msaccess_05:
    run: add-path-to-the-implementation/msaccess.cwl 
    in:
      msaccess_in_1: input_3
      msaccess_in_2: Mascot Server_04/Mascot Server_out_1
    out: [msaccess_out_1, msaccess_out_2, msaccess_out_3]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3956" # N-Quads
    outputSource: msaccess_05/msaccess_out_1
