# WorkflowNo_250
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_250
doc: A workflow including the tool(s) MyriMatch, Multi-Q, MSiReader, dig, esimsa.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_3162" # MAGE-TAB
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  MyriMatch_01:
    run: add-path-to-the-implementation/MyriMatch.cwl 
    in:
      MyriMatch_in_1: input_1
      MyriMatch_in_2: input_3
    out: [MyriMatch_out_1]
  Multi-Q_02:
    run: add-path-to-the-implementation/Multi-Q.cwl 
    in:
      Multi-Q_in_1: input_1
      Multi-Q_in_2: MyriMatch_01/MyriMatch_out_1
    out: [Multi-Q_out_1]
  MSiReader_03:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: Multi-Q_02/Multi-Q_out_1
    out: [MSiReader_out_1, MSiReader_out_2]
  dig_04:
    run: add-path-to-the-implementation/dig.cwl 
    in:
      dig_in_1: input_3
    out: [dig_out_1]
  esimsa_05:
    run: add-path-to-the-implementation/esimsa.cwl 
    in:
      esimsa_in_1: input_2
      esimsa_in_2: dig_04/dig_out_1
      esimsa_in_3: MSiReader_03/MSiReader_out_2
    out: [esimsa_out_1, esimsa_out_2, esimsa_out_3]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_1350" # MEME Dirichlet prior
    outputSource: esimsa_05/esimsa_out_1
