# WorkflowNo_1236
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1236
doc: A workflow including the tool(s) MaxQuant, MSiReader, nontarget, ComPIL, PEAKS Q.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1216" # unambiguous pure rna sequence
  input_2:
    type: File
    format: "http://edamontology.org/format_3913" # Loom
  input_3:
    type: File
    format: "http://edamontology.org/format_3620" # xlsx
steps:
  MaxQuant_01:
    run: add-path-to-the-implementation/MaxQuant.cwl 
    in:
      MaxQuant_in_1: input_3
    out: [MaxQuant_out_1, MaxQuant_out_2]
  MSiReader_02:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: MaxQuant_01/MaxQuant_out_1
    out: [MSiReader_out_1, MSiReader_out_2]
  nontarget_03:
    run: add-path-to-the-implementation/nontarget.cwl 
    in:
      nontarget_in_1: input_1
      nontarget_in_2: input_1
      nontarget_in_3: MSiReader_02/MSiReader_out_2
    out: [nontarget_out_1, nontarget_out_2, nontarget_out_3]
  ComPIL_04:
    run: add-path-to-the-implementation/ComPIL.cwl 
    in:
      ComPIL_in_1: nontarget_03/nontarget_out_3
    out: [ComPIL_out_1]
  PEAKS Q_05:
    run: add-path-to-the-implementation/PEAKS Q.cwl 
    in:
      PEAKS Q_in_1: ComPIL_04/ComPIL_out_1
    out: [PEAKS Q_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_2311" # EMBL-HTML
    outputSource: PEAKS Q_05/PEAKS Q_out_1
