# WorkflowNo_223
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_223
doc: A workflow including the tool(s) PEAKS DB, OpenMS, InDigestion, PChopper, DIA-Umpire.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3477" # Cytoscape input file format
steps:
  PEAKS DB_01:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_1
      PEAKS DB_in_2: input_2
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_02:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_2
      OpenMS_in_3: PEAKS DB_01/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  InDigestion_03:
    run: add-path-to-the-implementation/InDigestion.cwl 
    in:
      InDigestion_in_1: input_3
    out: [InDigestion_out_1, InDigestion_out_2, InDigestion_out_3]
  PChopper_04:
    run: add-path-to-the-implementation/PChopper.cwl 
    in:
      PChopper_in_1: InDigestion_03/InDigestion_out_3
    out: [PChopper_out_1]
  DIA-Umpire_05:
    run: add-path-to-the-implementation/DIA-Umpire.cwl 
    in:
      DIA-Umpire_in_1: input_1
      DIA-Umpire_in_2: OpenMS_02/OpenMS_out_2
      DIA-Umpire_in_3: PChopper_04/PChopper_out_1
    out: [DIA-Umpire_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3162" # MAGE-TAB
    outputSource: DIA-Umpire_05/DIA-Umpire_out_1
