# WorkflowNo_775
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_775
doc: A workflow including the tool(s) XTandemPipeline, XTandem Parser, TopPIC, XTandemPipeline, Libra.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3578" # IDAT
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3711" # X!Tandem XML
steps:
  XTandemPipeline_01:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: input_3
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  XTandem Parser_02:
    run: add-path-to-the-implementation/XTandem Parser.cwl 
    in:
      XTandem Parser_in_1: XTandemPipeline_01/XTandemPipeline_out_1
    out: [XTandem Parser_out_1, XTandem Parser_out_2]
  TopPIC_03:
    run: add-path-to-the-implementation/TopPIC.cwl 
    in:
      TopPIC_in_1: XTandem Parser_02/XTandem Parser_out_2
      TopPIC_in_2: input_2
    out: [TopPIC_out_1, TopPIC_out_2]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: TopPIC_03/TopPIC_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Libra_05:
    run: add-path-to-the-implementation/Libra.cwl 
    in:
      Libra_in_1: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Libra_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: Libra_05/Libra_out_1
