# WorkflowNo_1702
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1702
doc: A workflow including the tool(s) ProSight Lite, PEAKS DB, OpenMS, msaccess, qcmetrics.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_1963" # UniProtKB format
  input_3:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
steps:
  ProSight Lite_01:
    run: add-path-to-the-implementation/ProSight Lite.cwl 
    in:
      ProSight Lite_in_1: input_3
      ProSight Lite_in_2: input_1
      ProSight Lite_in_3: input_2
    out: [ProSight Lite_out_1, ProSight Lite_out_2]
  PEAKS DB_02:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_3
      PEAKS DB_in_2: input_1
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_03:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: ProSight Lite_01/ProSight Lite_out_1
      OpenMS_in_2: input_1
      OpenMS_in_3: PEAKS DB_02/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  msaccess_04:
    run: add-path-to-the-implementation/msaccess.cwl 
    in:
      msaccess_in_1: input_3
      msaccess_in_2: OpenMS_03/OpenMS_out_1
    out: [msaccess_out_1, msaccess_out_2, msaccess_out_3]
  qcmetrics_05:
    run: add-path-to-the-implementation/qcmetrics.cwl 
    in:
      qcmetrics_in_1: msaccess_04/msaccess_out_1
    out: [qcmetrics_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_2532" # GenBank-HTML
    outputSource: qcmetrics_05/qcmetrics_out_1
