# WorkflowNo_120
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_120
doc: A workflow including the tool(s) msmsEDA, Graph Extract, ProSight Lite, MS-Fit, Quant.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3652" # dta
  input_2:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
  input_3:
    type: File
    format: "http://edamontology.org/format_1963" # UniProtKB format
steps:
  msmsEDA_01:
    run: add-path-to-the-implementation/msmsEDA.cwl 
    in:
      msmsEDA_in_1: input_2
    out: [msmsEDA_out_1, msmsEDA_out_2, msmsEDA_out_3]
  Graph Extract_02:
    run: add-path-to-the-implementation/Graph Extract.cwl 
    in:
      Graph Extract_in_1: msmsEDA_01/msmsEDA_out_2
    out: [Graph Extract_out_1]
  ProSight Lite_03:
    run: add-path-to-the-implementation/ProSight Lite.cwl 
    in:
      ProSight Lite_in_1: input_2
      ProSight Lite_in_2: Graph Extract_02/Graph Extract_out_1
      ProSight Lite_in_3: input_3
    out: [ProSight Lite_out_1, ProSight Lite_out_2]
  MS-Fit_04:
    run: add-path-to-the-implementation/MS-Fit.cwl 
    in:
      MS-Fit_in_1: ProSight Lite_03/ProSight Lite_out_1
    out: [MS-Fit_out_1]
  Quant_05:
    run: add-path-to-the-implementation/Quant.cwl 
    in:
      Quant_in_1: input_1
      Quant_in_2: MS-Fit_04/MS-Fit_out_1
    out: [Quant_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3468" # xls
    outputSource: Quant_05/Quant_out_1
