# WorkflowNo_655
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_655
doc: A workflow including the tool(s) esimsa2D, esimsa2D, TopPIC, XTandemPipeline, Libra.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_1972" # NCBI format
  input_3:
    type: File
    format: "http://edamontology.org/format_1960" # Staden format
steps:
  esimsa2D_01:
    run: add-path-to-the-implementation/esimsa2D.cwl 
    in:
      esimsa2D_in_1: input_2
      esimsa2D_in_2: input_3
      esimsa2D_in_3: input_3
    out: [esimsa2D_out_1, esimsa2D_out_2, esimsa2D_out_3]
  esimsa2D_02:
    run: add-path-to-the-implementation/esimsa2D.cwl 
    in:
      esimsa2D_in_1: input_2
      esimsa2D_in_2: esimsa2D_01/esimsa2D_out_1
      esimsa2D_in_3: input_3
    out: [esimsa2D_out_1, esimsa2D_out_2, esimsa2D_out_3]
  TopPIC_03:
    run: add-path-to-the-implementation/TopPIC.cwl 
    in:
      TopPIC_in_1: esimsa2D_02/esimsa2D_out_2
      TopPIC_in_2: input_1
    out: [TopPIC_out_1, TopPIC_out_2]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: TopPIC_03/TopPIC_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Libra_05:
    run: add-path-to-the-implementation/Libra.cwl 
    in:
      Libra_in_1: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Libra_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: Libra_05/Libra_out_1
