# WorkflowNo_640
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_640
doc: A workflow including the tool(s) DeconMSn, DeconMSn, TopPIC, XTandemPipeline, Quant.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3712" # Thermo RAW
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3330" # PO
steps:
  DeconMSn_01:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_1
      DeconMSn_in_2: input_1
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  DeconMSn_02:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_1
      DeconMSn_in_2: input_1
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  TopPIC_03:
    run: add-path-to-the-implementation/TopPIC.cwl 
    in:
      TopPIC_in_1: DeconMSn_02/DeconMSn_out_3
      TopPIC_in_2: input_2
    out: [TopPIC_out_1, TopPIC_out_2]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: TopPIC_03/TopPIC_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Quant_05:
    run: add-path-to-the-implementation/Quant.cwl 
    in:
      Quant_in_1: DeconMSn_01/DeconMSn_out_3
      Quant_in_2: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Quant_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3468" # xls
    outputSource: Quant_05/Quant_out_1
