# WorkflowNo_43
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_43
doc: A workflow including the tool(s) CrosstalkDB, Graph Extract, ProFound, OpenMS, PVIEW.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3752" # CSV
steps:
  CrosstalkDB_01:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: input_3
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  Graph Extract_02:
    run: add-path-to-the-implementation/Graph Extract.cwl 
    in:
      Graph Extract_in_1: CrosstalkDB_01/CrosstalkDB_out_4
    out: [Graph Extract_out_1]
  ProFound_03:
    run: add-path-to-the-implementation/ProFound.cwl 
    in:
      ProFound_in_1: Graph Extract_02/Graph Extract_out_1
    out: [ProFound_out_1]
  OpenMS_04:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_2
      OpenMS_in_3: ProFound_03/ProFound_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  PVIEW_05:
    run: add-path-to-the-implementation/PVIEW.cwl 
    in:
      PVIEW_in_1: input_2
      PVIEW_in_2: input_1
      PVIEW_in_3: OpenMS_04/OpenMS_out_1
    out: [PVIEW_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_1989" # markx3
    outputSource: PVIEW_05/PVIEW_out_1
