# WorkflowNo_57
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_57
doc: A workflow including the tool(s) CrosstalkDB, PRIDE Toolsuite, Percolator, OpenMS, PeptideShaker.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3752" # CSV
  input_2:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  CrosstalkDB_01:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: input_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  PRIDE Toolsuite_02:
    run: add-path-to-the-implementation/PRIDE Toolsuite.cwl 
    in:
      PRIDE Toolsuite_in_1: CrosstalkDB_01/CrosstalkDB_out_4
    out: [PRIDE Toolsuite_out_1]
  Percolator_03:
    run: add-path-to-the-implementation/Percolator.cwl 
    in:
      Percolator_in_1: PRIDE Toolsuite_02/PRIDE Toolsuite_out_1
    out: [Percolator_out_1]
  OpenMS_04:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_2
      OpenMS_in_2: input_3
      OpenMS_in_3: Percolator_03/Percolator_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  PeptideShaker_05:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_3
      PeptideShaker_in_2: OpenMS_04/OpenMS_out_1
      PeptideShaker_in_3: input_2
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3579" # JPG
    outputSource: PeptideShaker_05/PeptideShaker_out_1
