# WorkflowNo_1007
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1007
doc: A workflow including the tool(s) dig2, MS-GF+, msaccess, XTandemPipeline, Libra.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3712" # Thermo RAW
  input_2:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_3:
    type: File
    format: "http://edamontology.org/format_1332" # FASTA search results format
steps:
  dig2_01:
    run: add-path-to-the-implementation/dig2.cwl 
    in:
      dig2_in_1: input_3
    out: [dig2_out_1]
  MS-GF+_02:
    run: add-path-to-the-implementation/MS-GF+.cwl 
    in:
      MS-GF+_in_1: input_2
      MS-GF+_in_2: dig2_01/dig2_out_1
    out: [MS-GF+_out_1, MS-GF+_out_2]
  msaccess_03:
    run: add-path-to-the-implementation/msaccess.cwl 
    in:
      msaccess_in_1: input_1
      msaccess_in_2: MS-GF+_02/MS-GF+_out_1
    out: [msaccess_out_1, msaccess_out_2, msaccess_out_3]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: msaccess_03/msaccess_out_2
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Libra_05:
    run: add-path-to-the-implementation/Libra.cwl 
    in:
      Libra_in_1: XTandemPipeline_04/XTandemPipeline_out_1
    out: [Libra_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: Libra_05/Libra_out_1
