# WorkflowNo_1052
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1052
doc: A workflow including the tool(s) PECAN (PEptide-Centric Analysis), Mascot Server, XTandem Parser, msmsEDA, MSiReader.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3682" # imzML metadata file
  input_2:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_3:
    type: File
    format: "http://edamontology.org/format_3162" # MAGE-TAB
steps:
  PECAN (PEptide-Centric Analysis)_01:
    run: add-path-to-the-implementation/PECAN (PEptide-Centric Analysis).cwl 
    in:
      PECAN (PEptide-Centric Analysis)_in_1: input_2
      PECAN (PEptide-Centric Analysis)_in_2: input_3
    out: [PECAN (PEptide-Centric Analysis)_out_1, PECAN (PEptide-Centric Analysis)_out_2]
  Mascot Server_02:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: input_1
      Mascot Server_in_2: PECAN (PEptide-Centric Analysis)_01/PECAN (PEptide-Centric Analysis)_out_2
    out: [Mascot Server_out_1]
  XTandem Parser_03:
    run: add-path-to-the-implementation/XTandem Parser.cwl 
    in:
      XTandem Parser_in_1: Mascot Server_02/Mascot Server_out_1
    out: [XTandem Parser_out_1, XTandem Parser_out_2]
  msmsEDA_04:
    run: add-path-to-the-implementation/msmsEDA.cwl 
    in:
      msmsEDA_in_1: XTandem Parser_03/XTandem Parser_out_2
    out: [msmsEDA_out_1, msmsEDA_out_2, msmsEDA_out_3]
  MSiReader_05:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: msmsEDA_04/msmsEDA_out_3
    out: [MSiReader_out_1, MSiReader_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3620" # xlsx
    outputSource: MSiReader_05/MSiReader_out_1
