# WorkflowNo_1564
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1564
doc: A workflow including the tool(s) MS-Isotope, PeptideProphet, OpenMS, PRIDE Toolsuite, MS-Digest.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_2:
    type: File
    format: "http://edamontology.org/format_1957" # raw
  input_3:
    type: File
    format: "http://edamontology.org/format_3770" # UniProtKB XML
steps:
  MS-Isotope_01:
    run: add-path-to-the-implementation/MS-Isotope.cwl 
    in:
      MS-Isotope_in_1: input_2
    out: [MS-Isotope_out_1]
  PeptideProphet_02:
    run: add-path-to-the-implementation/PeptideProphet.cwl 
    in:
      PeptideProphet_in_1: MS-Isotope_01/MS-Isotope_out_1
    out: [PeptideProphet_out_1]
  OpenMS_03:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_3
      OpenMS_in_2: input_1
      OpenMS_in_3: PeptideProphet_02/PeptideProphet_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  PRIDE Toolsuite_04:
    run: add-path-to-the-implementation/PRIDE Toolsuite.cwl 
    in:
      PRIDE Toolsuite_in_1: OpenMS_03/OpenMS_out_1
    out: [PRIDE Toolsuite_out_1]
  MS-Digest_05:
    run: add-path-to-the-implementation/MS-Digest.cwl 
    in:
      MS-Digest_in_1: input_2
      MS-Digest_in_2: PRIDE Toolsuite_04/PRIDE Toolsuite_out_1
    out: [MS-Digest_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3701" # Sequin format
    outputSource: MS-Digest_05/MS-Digest_out_1
