# WorkflowNo_1024
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1024
doc: A workflow including the tool(s) PGA, MeroX, PIA - Protein Inference Algorithms, Percolator, Libra.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3913" # Loom
  input_2:
    type: File
    format: "http://edamontology.org/format_3613" # ENCODE narrow peak format
  input_3:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
steps:
  PGA_01:
    run: add-path-to-the-implementation/PGA.cwl 
    in:
      PGA_in_1: input_2
    out: [PGA_out_1]
  MeroX_02:
    run: add-path-to-the-implementation/MeroX.cwl 
    in:
      MeroX_in_1: input_3
      MeroX_in_2: PGA_01/PGA_out_1
    out: [MeroX_out_1]
  PIA - Protein Inference Algorithms_03:
    run: add-path-to-the-implementation/PIA - Protein Inference Algorithms.cwl 
    in:
      PIA - Protein Inference Algorithms_in_1: MeroX_02/MeroX_out_1
    out: [PIA - Protein Inference Algorithms_out_1, PIA - Protein Inference Algorithms_out_2]
  Percolator_04:
    run: add-path-to-the-implementation/Percolator.cwl 
    in:
      Percolator_in_1: PIA - Protein Inference Algorithms_03/PIA - Protein Inference Algorithms_out_1
    out: [Percolator_out_1]
  Libra_05:
    run: add-path-to-the-implementation/Libra.cwl 
    in:
      Libra_in_1: Percolator_04/Percolator_out_1
    out: [Libra_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
    outputSource: Libra_05/Libra_out_1
