# WorkflowNo_41
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_41
doc: A workflow including the tool(s) ICPL_ESIQuant, PeptideShaker, PChopper, PEAKS DB, PEAKS Q.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_3247" # mzIdentML
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  ICPL_ESIQuant_01:
    run: add-path-to-the-implementation/ICPL_ESIQuant.cwl 
    in:
      ICPL_ESIQuant_in_1: input_1
    out: [ICPL_ESIQuant_out_1]
  PeptideShaker_02:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_3
      PeptideShaker_in_2: input_2
      PeptideShaker_in_3: ICPL_ESIQuant_01/ICPL_ESIQuant_out_1
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
  PChopper_03:
    run: add-path-to-the-implementation/PChopper.cwl 
    in:
      PChopper_in_1: PeptideShaker_02/PeptideShaker_out_2
    out: [PChopper_out_1]
  PEAKS DB_04:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_1
      PEAKS DB_in_2: PChopper_03/PChopper_out_1
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  PEAKS Q_05:
    run: add-path-to-the-implementation/PEAKS Q.cwl 
    in:
      PEAKS Q_in_1: PEAKS DB_04/PEAKS DB_out_1
    out: [PEAKS Q_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_2532" # GenBank-HTML
    outputSource: PEAKS Q_05/PEAKS Q_out_1
