# WorkflowNo_272
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_272
doc: A workflow including the tool(s) DeconMSn, DeconMSn, MeroX, Peppy, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3712" # Thermo RAW
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3313" # BLC
steps:
  DeconMSn_01:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_1
      DeconMSn_in_2: input_1
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  DeconMSn_02:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_1
      DeconMSn_in_2: input_1
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  MeroX_03:
    run: add-path-to-the-implementation/MeroX.cwl 
    in:
      MeroX_in_1: DeconMSn_02/DeconMSn_out_3
      MeroX_in_2: input_2
    out: [MeroX_out_1]
  Peppy_04:
    run: add-path-to-the-implementation/Peppy.cwl 
    in:
      Peppy_in_1: DeconMSn_01/DeconMSn_out_3
      Peppy_in_2: MeroX_03/MeroX_out_1
      Peppy_in_3: input_2
    out: [Peppy_out_1, Peppy_out_2]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: DeconMSn_01/DeconMSn_out_1
      OpenMS_in_2: input_2
      OpenMS_in_3: Peppy_04/Peppy_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: OpenMS_05/OpenMS_out_1
