# WorkflowNo_662
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_662
doc: A workflow including the tool(s) libmgf, PeptideShaker, GenePattern, Percolator, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_3652" # dta
  input_3:
    type: File
    format: "http://edamontology.org/format_3247" # mzIdentML
steps:
  libmgf_01:
    run: add-path-to-the-implementation/libmgf.cwl 
    in:
      libmgf_in_1: input_2
    out: [libmgf_out_1]
  PeptideShaker_02:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_1
      PeptideShaker_in_2: input_3
      PeptideShaker_in_3: libmgf_01/libmgf_out_1
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
  GenePattern_03:
    run: add-path-to-the-implementation/GenePattern.cwl 
    in:
      GenePattern_in_1: PeptideShaker_02/PeptideShaker_out_4
    out: [GenePattern_out_1]
  Percolator_04:
    run: add-path-to-the-implementation/Percolator.cwl 
    in:
      Percolator_in_1: input_3
    out: [Percolator_out_1]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_2
      OpenMS_in_2: GenePattern_03/GenePattern_out_1
      OpenMS_in_3: Percolator_04/Percolator_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3683" # qcML
    outputSource: OpenMS_05/OpenMS_out_1
