# WorkflowNo_1271
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1271
doc: A workflow including the tool(s) PVIEW, Multi-Q, OpenSWATH, PVIEW, LimmaRP.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3655" # pepXML
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
steps:
  PVIEW_01:
    run: add-path-to-the-implementation/PVIEW.cwl 
    in:
      PVIEW_in_1: input_2
      PVIEW_in_2: input_3
      PVIEW_in_3: input_1
    out: [PVIEW_out_1]
  Multi-Q_02:
    run: add-path-to-the-implementation/Multi-Q.cwl 
    in:
      Multi-Q_in_1: input_3
      Multi-Q_in_2: input_1
    out: [Multi-Q_out_1]
  OpenSWATH_03:
    run: add-path-to-the-implementation/OpenSWATH.cwl 
    in:
      OpenSWATH_in_1: Multi-Q_02/Multi-Q_out_1
    out: [OpenSWATH_out_1]
  PVIEW_04:
    run: add-path-to-the-implementation/PVIEW.cwl 
    in:
      PVIEW_in_1: input_2
      PVIEW_in_2: OpenSWATH_03/OpenSWATH_out_1
      PVIEW_in_3: input_1
    out: [PVIEW_out_1]
  LimmaRP_05:
    run: add-path-to-the-implementation/LimmaRP.cwl 
    in:
      LimmaRP_in_1: PVIEW_01/PVIEW_out_1
      LimmaRP_in_2: PVIEW_04/PVIEW_out_1
    out: [LimmaRP_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3508" # PDF
    outputSource: LimmaRP_05/LimmaRP_out_1
