# WorkflowNo_67
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_67
doc: A workflow including the tool(s) PEAKS DB, OpenMS, PeptideShaker, PChopper, PEP-SiteFinder.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1476" # PDB
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
steps:
  PEAKS DB_01:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_3
      PEAKS DB_in_2: input_2
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_02:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_3
      OpenMS_in_2: input_2
      OpenMS_in_3: PEAKS DB_01/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  PeptideShaker_03:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_2
      PeptideShaker_in_2: OpenMS_02/OpenMS_out_1
      PeptideShaker_in_3: input_3
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
  PChopper_04:
    run: add-path-to-the-implementation/PChopper.cwl 
    in:
      PChopper_in_1: PeptideShaker_03/PeptideShaker_out_2
    out: [PChopper_out_1]
  PEP-SiteFinder_05:
    run: add-path-to-the-implementation/PEP-SiteFinder.cwl 
    in:
      PEP-SiteFinder_in_1: PChopper_04/PChopper_out_1
      PEP-SiteFinder_in_2: input_1
    out: [PEP-SiteFinder_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_1476" # PDB
    outputSource: PEP-SiteFinder_05/PEP-SiteFinder_out_1
