# WorkflowNo_130
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_130
doc: A workflow including the tool(s) CrosstalkDB, CrosstalkDB, mspire_mspire-sequest, PEAKS DB, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3752" # CSV
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3653" # pkl
steps:
  CrosstalkDB_01:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: input_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  CrosstalkDB_02:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: CrosstalkDB_01/CrosstalkDB_out_3
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  mspire_mspire-sequest_03:
    run: add-path-to-the-implementation/mspire_mspire-sequest.cwl 
    in:
      mspire_mspire-sequest_in_1: CrosstalkDB_02/CrosstalkDB_out_4
    out: [mspire_mspire-sequest_out_1]
  PEAKS DB_04:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_3
      PEAKS DB_in_2: input_2
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: mspire_mspire-sequest_03/mspire_mspire-sequest_out_1
      OpenMS_in_2: input_2
      OpenMS_in_3: PEAKS DB_04/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3764" # idXML
    outputSource: OpenMS_05/OpenMS_out_1
