# WorkflowNo_260
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_260
doc: A workflow including the tool(s) PIA - Protein Inference Algorithms, msaccess, Graph Extract, MS-Fit, Quant.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3702" # MSF
  input_2:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_3:
    type: File
    format: "http://edamontology.org/format_3652" # dta
steps:
  PIA - Protein Inference Algorithms_01:
    run: add-path-to-the-implementation/PIA - Protein Inference Algorithms.cwl 
    in:
      PIA - Protein Inference Algorithms_in_1: input_1
    out: [PIA - Protein Inference Algorithms_out_1, PIA - Protein Inference Algorithms_out_2]
  msaccess_02:
    run: add-path-to-the-implementation/msaccess.cwl 
    in:
      msaccess_in_1: input_2
      msaccess_in_2: PIA - Protein Inference Algorithms_01/PIA - Protein Inference Algorithms_out_1
    out: [msaccess_out_1, msaccess_out_2, msaccess_out_3]
  Graph Extract_03:
    run: add-path-to-the-implementation/Graph Extract.cwl 
    in:
      Graph Extract_in_1: msaccess_02/msaccess_out_3
    out: [Graph Extract_out_1]
  MS-Fit_04:
    run: add-path-to-the-implementation/MS-Fit.cwl 
    in:
      MS-Fit_in_1: Graph Extract_03/Graph Extract_out_1
    out: [MS-Fit_out_1]
  Quant_05:
    run: add-path-to-the-implementation/Quant.cwl 
    in:
      Quant_in_1: input_3
      Quant_in_2: MS-Fit_04/MS-Fit_out_1
    out: [Quant_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3468" # xls
    outputSource: Quant_05/Quant_out_1
