# WorkflowNo_1573
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1573
doc: A workflow including the tool(s) InDigestion, MassMatrix, OpenMS, DeconMSn, PeptideShaker.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_3257" # Notation3
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  InDigestion_01:
    run: add-path-to-the-implementation/InDigestion.cwl 
    in:
      InDigestion_in_1: input_2
    out: [InDigestion_out_1, InDigestion_out_2, InDigestion_out_3]
  MassMatrix_02:
    run: add-path-to-the-implementation/MassMatrix.cwl 
    in:
      MassMatrix_in_1: input_1
      MassMatrix_in_2: InDigestion_01/InDigestion_out_3
    out: [MassMatrix_out_1]
  OpenMS_03:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_3
      OpenMS_in_3: MassMatrix_02/MassMatrix_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  DeconMSn_04:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_1
      DeconMSn_in_2: input_1
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  PeptideShaker_05:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_3
      PeptideShaker_in_2: OpenMS_03/OpenMS_out_1
      PeptideShaker_in_3: DeconMSn_04/DeconMSn_out_1
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3579" # JPG
    outputSource: PeptideShaker_05/PeptideShaker_out_1
