# WorkflowNo_132
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_132
doc: A workflow including the tool(s) MS-Fit, OpenMS, MSiReader, esimsa2D, esimsa.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_3770" # UniProtKB XML
  input_3:
    type: File
    format: "http://edamontology.org/format_3785" # BioNLP Shared Task format
steps:
  MS-Fit_01:
    run: add-path-to-the-implementation/MS-Fit.cwl 
    in:
      MS-Fit_in_1: input_1
    out: [MS-Fit_out_1]
  OpenMS_02:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_2
      OpenMS_in_3: MS-Fit_01/MS-Fit_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  MSiReader_03:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_1
      MSiReader_in_2: OpenMS_02/OpenMS_out_2
    out: [MSiReader_out_1, MSiReader_out_2]
  esimsa2D_04:
    run: add-path-to-the-implementation/esimsa2D.cwl 
    in:
      esimsa2D_in_1: input_3
      esimsa2D_in_2: input_1
      esimsa2D_in_3: MSiReader_03/MSiReader_out_2
    out: [esimsa2D_out_1, esimsa2D_out_2, esimsa2D_out_3]
  esimsa_05:
    run: add-path-to-the-implementation/esimsa.cwl 
    in:
      esimsa_in_1: input_3
      esimsa_in_2: esimsa2D_04/esimsa2D_out_1
      esimsa_in_3: MSiReader_03/MSiReader_out_2
    out: [esimsa_out_1, esimsa_out_2, esimsa_out_3]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3881" # AMBER top
    outputSource: esimsa_05/esimsa_out_1
