# WorkflowNo_101
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_101
doc: A workflow including the tool(s) Peppy, OpenMS, dig, InDigestion, X Hunter.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
steps:
  Peppy_01:
    run: add-path-to-the-implementation/Peppy.cwl 
    in:
      Peppy_in_1: input_3
      Peppy_in_2: input_2
      Peppy_in_3: input_1
    out: [Peppy_out_1, Peppy_out_2]
  OpenMS_02:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_3
      OpenMS_in_2: input_1
      OpenMS_in_3: Peppy_01/Peppy_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  dig_03:
    run: add-path-to-the-implementation/dig.cwl 
    in:
      dig_in_1: OpenMS_02/OpenMS_out_2
    out: [dig_out_1]
  InDigestion_04:
    run: add-path-to-the-implementation/InDigestion.cwl 
    in:
      InDigestion_in_1: dig_03/dig_out_1
    out: [InDigestion_out_1, InDigestion_out_2, InDigestion_out_3]
  X Hunter_05:
    run: add-path-to-the-implementation/X Hunter.cwl 
    in:
      X Hunter_in_1: input_3
      X Hunter_in_2: InDigestion_04/InDigestion_out_3
      X Hunter_in_3: input_3
    out: [X Hunter_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3711" # X!Tandem XML
    outputSource: X Hunter_05/X Hunter_out_1
