# WorkflowNo_277
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_277
doc: A workflow including the tool(s) MaxQuant, CrosstalkDB, MSiReader, XTandemPipeline, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3758" # SEQUEST .out file
  input_2:
    type: File
    format: "http://edamontology.org/format_3682" # imzML metadata file
  input_3:
    type: File
    format: "http://edamontology.org/format_3682" # imzML metadata file
steps:
  MaxQuant_01:
    run: add-path-to-the-implementation/MaxQuant.cwl 
    in:
      MaxQuant_in_1: input_1
    out: [MaxQuant_out_1, MaxQuant_out_2]
  CrosstalkDB_02:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: MaxQuant_01/MaxQuant_out_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  MSiReader_03:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_2
      MSiReader_in_2: CrosstalkDB_02/CrosstalkDB_out_2
    out: [MSiReader_out_1, MSiReader_out_2]
  XTandemPipeline_04:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: input_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: MSiReader_03/MSiReader_out_2
      OpenMS_in_2: input_3
      OpenMS_in_3: XTandemPipeline_04/XTandemPipeline_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: OpenMS_05/OpenMS_out_1
