# WorkflowNo_1025
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1025
doc: A workflow including the tool(s) XTandemPipeline, PEAKS DB, PRIDE Toolsuite, PeptideProphet, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_2:
    type: File
    format: "http://edamontology.org/format_3758" # SEQUEST .out file
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  XTandemPipeline_01:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: input_2
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  PEAKS DB_02:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_1
      PEAKS DB_in_2: input_3
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  PRIDE Toolsuite_03:
    run: add-path-to-the-implementation/PRIDE Toolsuite.cwl 
    in:
      PRIDE Toolsuite_in_1: XTandemPipeline_01/XTandemPipeline_out_1
    out: [PRIDE Toolsuite_out_1]
  PeptideProphet_04:
    run: add-path-to-the-implementation/PeptideProphet.cwl 
    in:
      PeptideProphet_in_1: PEAKS DB_02/PEAKS DB_out_1
    out: [PeptideProphet_out_1]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: PRIDE Toolsuite_03/PRIDE Toolsuite_out_1
      OpenMS_in_3: PeptideProphet_04/PeptideProphet_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: OpenMS_05/OpenMS_out_1
