# WorkflowNo_1144
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1144
doc: A workflow including the tool(s) PRIDE Toolsuite, massXpert, massXpert, MyriMatch, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3834" # mzData
steps:
  PRIDE Toolsuite_01:
    run: add-path-to-the-implementation/PRIDE Toolsuite.cwl 
    in:
      PRIDE Toolsuite_in_1: input_1
    out: [PRIDE Toolsuite_out_1]
  massXpert_02:
    run: add-path-to-the-implementation/massXpert.cwl 
    in:
      massXpert_in_1: input_1
      massXpert_in_2: PRIDE Toolsuite_01/PRIDE Toolsuite_out_1
    out: [massXpert_out_1, massXpert_out_2]
  massXpert_03:
    run: add-path-to-the-implementation/massXpert.cwl 
    in:
      massXpert_in_1: massXpert_02/massXpert_out_1
      massXpert_in_2: massXpert_02/massXpert_out_2
    out: [massXpert_out_1, massXpert_out_2]
  MyriMatch_04:
    run: add-path-to-the-implementation/MyriMatch.cwl 
    in:
      MyriMatch_in_1: input_3
      MyriMatch_in_2: input_2
    out: [MyriMatch_out_1]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_3
      OpenMS_in_2: massXpert_03/massXpert_out_2
      OpenMS_in_3: MyriMatch_04/MyriMatch_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: OpenMS_05/OpenMS_out_1
