# WorkflowNo_1725
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1725
doc: A workflow including the tool(s) MSD File Reader, CPM, OpenSWATH, Mascot Server, PeptideShaker.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_3622" # Gemini SQLite format
  input_3:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
steps:
  MSD File Reader_01:
    run: add-path-to-the-implementation/MSD File Reader.cwl 
    in: []
    out: [MSD File Reader_out_1]
  CPM_02:
    run: add-path-to-the-implementation/CPM.cwl 
    in:
      CPM_in_1: MSD File Reader_01/MSD File Reader_out_1
      CPM_in_2: MSD File Reader_01/MSD File Reader_out_1
    out: [CPM_out_1, CPM_out_2]
  OpenSWATH_03:
    run: add-path-to-the-implementation/OpenSWATH.cwl 
    in:
      OpenSWATH_in_1: input_2
      OpenSWATH_in_2: CPM_02/CPM_out_1
    out: [OpenSWATH_out_1]
  Mascot Server_04:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: OpenSWATH_03/OpenSWATH_out_1
      Mascot Server_in_2: input_3
    out: [Mascot Server_out_1]
  PeptideShaker_05:
    run: add-path-to-the-implementation/PeptideShaker.cwl 
    in:
      PeptideShaker_in_1: input_1
      PeptideShaker_in_2: Mascot Server_04/Mascot Server_out_1
      PeptideShaker_in_3: input_3
    out: [PeptideShaker_out_1, PeptideShaker_out_2, PeptideShaker_out_3, PeptideShaker_out_4]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_1432" # Phylip character frequencies format
    outputSource: PeptideShaker_05/PeptideShaker_out_1
