# WorkflowNo_102
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_102
doc: A workflow including the tool(s) ProSight Lite, MSD File Reader, MSD File Reader, OpenSWATH, Mascot Server.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3747" # protXML
  input_2:
    type: File
    format: "http://edamontology.org/format_1963" # UniProtKB format
  input_3:
    type: File
    format: "http://edamontology.org/format_1504" # aaindex
steps:
  ProSight Lite_01:
    run: add-path-to-the-implementation/ProSight Lite.cwl 
    in:
      ProSight Lite_in_1: input_1
      ProSight Lite_in_2: input_3
      ProSight Lite_in_3: input_2
    out: [ProSight Lite_out_1, ProSight Lite_out_2]
  MSD File Reader_02:
    run: add-path-to-the-implementation/MSD File Reader.cwl 
    in: []
    out: [MSD File Reader_out_1]
  MSD File Reader_03:
    run: add-path-to-the-implementation/MSD File Reader.cwl 
    in: []
    out: [MSD File Reader_out_1]
  OpenSWATH_04:
    run: add-path-to-the-implementation/OpenSWATH.cwl 
    in:
      OpenSWATH_in_1: ProSight Lite_01/ProSight Lite_out_1
      OpenSWATH_in_2: MSD File Reader_02/MSD File Reader_out_1
    out: [OpenSWATH_out_1]
  Mascot Server_05:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: OpenSWATH_04/OpenSWATH_out_1
      Mascot Server_in_2: MSD File Reader_03/MSD File Reader_out_1
    out: [Mascot Server_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: Mascot Server_05/Mascot Server_out_1
