# WorkflowNo_1660
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1660
doc: A workflow including the tool(s) XTandem Parser, TopPIC, XTandemPipeline, Multi-Q, CrosstalkDB.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3711" # X!Tandem XML
steps:
  XTandem Parser_01:
    run: add-path-to-the-implementation/XTandem Parser.cwl 
    in:
      XTandem Parser_in_1: input_3
    out: [XTandem Parser_out_1, XTandem Parser_out_2]
  TopPIC_02:
    run: add-path-to-the-implementation/TopPIC.cwl 
    in:
      TopPIC_in_1: XTandem Parser_01/XTandem Parser_out_2
      TopPIC_in_2: input_2
    out: [TopPIC_out_1, TopPIC_out_2]
  XTandemPipeline_03:
    run: add-path-to-the-implementation/XTandemPipeline.cwl 
    in:
      XTandemPipeline_in_1: TopPIC_02/TopPIC_out_1
    out: [XTandemPipeline_out_1, XTandemPipeline_out_2]
  Multi-Q_04:
    run: add-path-to-the-implementation/Multi-Q.cwl 
    in:
      Multi-Q_in_1: input_1
      Multi-Q_in_2: XTandemPipeline_03/XTandemPipeline_out_1
    out: [Multi-Q_out_1]
  CrosstalkDB_05:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: Multi-Q_04/Multi-Q_out_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3752" # CSV
    outputSource: CrosstalkDB_05/CrosstalkDB_out_1
