# WorkflowNo_1010
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1010
doc: A workflow including the tool(s) DeconMSn, PEAKS DB, OpenMS, MassChroQ, OpenSWATH.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
  input_2:
    type: File
    format: "http://edamontology.org/format_3712" # Thermo RAW
  input_3:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
steps:
  DeconMSn_01:
    run: add-path-to-the-implementation/DeconMSn.cwl 
    in:
      DeconMSn_in_1: input_2
      DeconMSn_in_2: input_2
    out: [DeconMSn_out_1, DeconMSn_out_2, DeconMSn_out_3]
  PEAKS DB_02:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: DeconMSn_01/DeconMSn_out_3
      PEAKS DB_in_2: input_3
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_03:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_1
      OpenMS_in_2: input_3
      OpenMS_in_3: PEAKS DB_02/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  MassChroQ_04:
    run: add-path-to-the-implementation/MassChroQ.cwl 
    in:
      MassChroQ_in_1: OpenMS_03/OpenMS_out_1
    out: [MassChroQ_out_1]
  OpenSWATH_05:
    run: add-path-to-the-implementation/OpenSWATH.cwl 
    in:
      OpenSWATH_in_1: MassChroQ_04/MassChroQ_out_1
    out: [OpenSWATH_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3622" # Gemini SQLite format
    outputSource: OpenSWATH_05/OpenSWATH_out_1
