# WorkflowNo_1234
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1234
doc: A workflow including the tool(s) ProSight Lite, ProFound, OpenMS, ProSight Lite, msaccess.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1963" # UniProtKB format
  input_2:
    type: File
    format: "http://edamontology.org/format_2549" # OBO
  input_3:
    type: File
    format: "http://edamontology.org/format_2549" # OBO
steps:
  ProSight Lite_01:
    run: add-path-to-the-implementation/ProSight Lite.cwl 
    in:
      ProSight Lite_in_1: input_2
      ProSight Lite_in_2: input_3
      ProSight Lite_in_3: input_1
    out: [ProSight Lite_out_1, ProSight Lite_out_2]
  ProFound_02:
    run: add-path-to-the-implementation/ProFound.cwl 
    in:
      ProFound_in_1: ProSight Lite_01/ProSight Lite_out_1
    out: [ProFound_out_1]
  OpenMS_03:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_2
      OpenMS_in_2: input_3
      OpenMS_in_3: ProFound_02/ProFound_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  ProSight Lite_04:
    run: add-path-to-the-implementation/ProSight Lite.cwl 
    in:
      ProSight Lite_in_1: input_2
      ProSight Lite_in_2: input_3
      ProSight Lite_in_3: input_1
    out: [ProSight Lite_out_1, ProSight Lite_out_2]
  msaccess_05:
    run: add-path-to-the-implementation/msaccess.cwl 
    in:
      msaccess_in_1: ProSight Lite_04/ProSight Lite_out_1
      msaccess_in_2: OpenMS_03/OpenMS_out_1
    out: [msaccess_out_1, msaccess_out_2, msaccess_out_3]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3881" # AMBER top
    outputSource: msaccess_05/msaccess_out_1
