# WorkflowNo_222
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_222
doc: A workflow including the tool(s) msmsEDA, MSiReader, MSiReader, PeptideProphet, OpenMS.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_2352" # BioXSD (XML)
  input_2:
    type: File
    format: "http://edamontology.org/format_2310" # FASTA-HTML
  input_3:
    type: File
    format: "http://edamontology.org/format_3682" # imzML metadata file
steps:
  msmsEDA_01:
    run: add-path-to-the-implementation/msmsEDA.cwl 
    in:
      msmsEDA_in_1: input_3
    out: [msmsEDA_out_1, msmsEDA_out_2, msmsEDA_out_3]
  MSiReader_02:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_3
      MSiReader_in_2: msmsEDA_01/msmsEDA_out_2
    out: [MSiReader_out_1, MSiReader_out_2]
  MSiReader_03:
    run: add-path-to-the-implementation/MSiReader.cwl 
    in:
      MSiReader_in_1: input_3
      MSiReader_in_2: MSiReader_02/MSiReader_out_1
    out: [MSiReader_out_1, MSiReader_out_2]
  PeptideProphet_04:
    run: add-path-to-the-implementation/PeptideProphet.cwl 
    in:
      PeptideProphet_in_1: input_2
    out: [PeptideProphet_out_1]
  OpenMS_05:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: MSiReader_03/MSiReader_out_2
      OpenMS_in_2: input_1
      OpenMS_in_3: PeptideProphet_04/PeptideProphet_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3652" # dta
    outputSource: OpenMS_05/OpenMS_out_1
