# WorkflowNo_1400
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_1400
doc: A workflow including the tool(s) MSGraph, InDigestion, esimsa2D, PECAN (PEptide-Centric Analysis), Mascot Server.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_3877" # XYZ
  input_2:
    type: File
    format: "http://edamontology.org/format_3244" # mzML
  input_3:
    type: File
    format: "http://edamontology.org/format_1960" # Staden format
steps:
  MSGraph_01:
    run: add-path-to-the-implementation/MSGraph.cwl 
    in:
      MSGraph_in_1: input_2
    out: [MSGraph_out_1, MSGraph_out_2]
  InDigestion_02:
    run: add-path-to-the-implementation/InDigestion.cwl 
    in:
      InDigestion_in_1: input_1
    out: [InDigestion_out_1, InDigestion_out_2, InDigestion_out_3]
  esimsa2D_03:
    run: add-path-to-the-implementation/esimsa2D.cwl 
    in:
      esimsa2D_in_1: input_3
      esimsa2D_in_2: MSGraph_01/MSGraph_out_1
      esimsa2D_in_3: MSGraph_01/MSGraph_out_1
    out: [esimsa2D_out_1, esimsa2D_out_2, esimsa2D_out_3]
  PECAN (PEptide-Centric Analysis)_04:
    run: add-path-to-the-implementation/PECAN (PEptide-Centric Analysis).cwl 
    in:
      PECAN (PEptide-Centric Analysis)_in_1: input_2
      PECAN (PEptide-Centric Analysis)_in_2: InDigestion_02/InDigestion_out_3
    out: [PECAN (PEptide-Centric Analysis)_out_1, PECAN (PEptide-Centric Analysis)_out_2]
  Mascot Server_05:
    run: add-path-to-the-implementation/Mascot Server.cwl 
    in:
      Mascot Server_in_1: esimsa2D_03/esimsa2D_out_1
      Mascot Server_in_2: PECAN (PEptide-Centric Analysis)_04/PECAN (PEptide-Centric Analysis)_out_2
    out: [Mascot Server_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3651" # MGF
    outputSource: Mascot Server_05/Mascot Server_out_1
