# WorkflowNo_3
# This workflow is generated by APE (https://github.com/sanctuuary/APE).
cwlVersion: v1.2
class: Workflow

label: WorkflowNo_3
doc: A workflow including the tool(s) PEAKS DB, OpenMS, PVIEW, CrosstalkDB, mspire_mspire-sequest.

inputs:
  input_1:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_2:
    type: File
    format: "http://edamontology.org/format_1929" # FASTA
  input_3:
    type: File
    format: "http://edamontology.org/format_3654" # mzXML
steps:
  PEAKS DB_01:
    run: add-path-to-the-implementation/PEAKS DB.cwl 
    in:
      PEAKS DB_in_1: input_3
      PEAKS DB_in_2: input_1
    out: [PEAKS DB_out_1, PEAKS DB_out_2]
  OpenMS_02:
    run: add-path-to-the-implementation/OpenMS.cwl 
    in:
      OpenMS_in_1: input_3
      OpenMS_in_2: input_1
      OpenMS_in_3: PEAKS DB_01/PEAKS DB_out_1
    out: [OpenMS_out_1, OpenMS_out_2]
  PVIEW_03:
    run: add-path-to-the-implementation/PVIEW.cwl 
    in:
      PVIEW_in_1: input_2
      PVIEW_in_2: input_3
      PVIEW_in_3: OpenMS_02/OpenMS_out_1
    out: [PVIEW_out_1]
  CrosstalkDB_04:
    run: add-path-to-the-implementation/CrosstalkDB.cwl 
    in:
      CrosstalkDB_in_1: PVIEW_03/PVIEW_out_1
    out: [CrosstalkDB_out_1, CrosstalkDB_out_2, CrosstalkDB_out_3, CrosstalkDB_out_4]
  mspire_mspire-sequest_05:
    run: add-path-to-the-implementation/mspire_mspire-sequest.cwl 
    in:
      mspire_mspire-sequest_in_1: CrosstalkDB_04/CrosstalkDB_out_3
    out: [mspire_mspire-sequest_out_1]
outputs:
  output_1:
    type: File
    format: "http://edamontology.org/format_3655" # pepXML
    outputSource: mspire_mspire-sequest_05/mspire_mspire-sequest_out_1
