import igraph

def sum_metric(graph, workflows): # cocitation metric 

    """
    Calculates the cocitation  metric for a given workflow and a given cocitation graph
    
    Parameters
    ----------
    graph : igraph.Graph
        Graph generated by igraph
    workflow, list of tuples with pairs of strings TODO: how do I write this? does it matter I wont have this format later anyways? 
        List of tuples of strings corresponding to the edges in the workflow. 

    """
    # List to  collect pairwise scores
    score_list = [] # TODO: can predefine the list length, does not matter this is temporary?

    for pair in workflows:
        cocite_score = 0
        neighbors_of_first = set(graph.neighbors(pair[0]))
        neighbors_of_second = set(graph.neighbors(pair[1]))

        # Count number of common neighbours
        common_neighbors = neighbors_of_first.intersection(neighbors_of_second)
        cocite_score = len(common_neighbors)
        score_list.append(cocite_score)

    # Then sum the scores or perform any other desired calculation
    # now normalising by WF length
    # maybe call this one "support", since that is basically what we have. 

    return sum(score_list)/len(score_list), score_list

def path_metric(G, workflow, included_tools): #TODO: how normalise this?
    # shortest path == shortest path of the subpaths. Thus:

    shortest_paths = []

    for edge in workflow:
        source = edge[0]
        target = edge[1]

        if source in included_tools and target in included_tools:
            shortest_paths.append(igraph.GraphBase.get_shortest_paths(source, to = target))
        else:
            shortest_paths.append(None)


    return shortest_paths